SELECT 
  k.COLUMN_NAME,
  k.REFERENCED_TABLE_NAME,
  k.REFERENCED_COLUMN_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE k
WHERE k.TABLE_SCHEMA = 'transactions'
  AND k.TABLE_NAME = 'transaction'
  AND k.REFERENCED_TABLE_NAME IS NOT NULL;
